In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Reading the Dataset
dataset = pd.read_csv('Airmean_Chennai.csv')
dataset=pd.get_dummies(dataset,drop_first=True)
dataset.head(5)

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,...,Date_2020-06-22,Date_2020-06-23,Date_2020-06-24,Date_2020-06-25,Date_2020-06-26,Date_2020-06-27,Date_2020-06-28,Date_2020-06-29,Date_2020-06-30,Date_2020-07-01
0,77.394417,149.388739,16.30,15.39,22.68,4.59,1.17,9.20,11.35,0.170000,...,0,0,0,0,0,0,0,0,0,0
1,77.394417,149.388739,16.49,13.42,23.09,7.83,1.23,8.61,9.16,0.130000,...,0,0,0,0,0,0,0,0,0,0
2,77.394417,149.388739,9.72,19.56,9.99,4.63,0.77,20.56,13.45,0.030000,...,0,0,0,0,0,0,0,0,0,0
3,77.394417,149.388739,9.60,16.20,11.71,5.23,1.00,20.56,10.33,2.120333,...,0,0,0,0,0,0,0,0,0,0
4,77.394417,149.388739,9.16,16.30,12.94,5.50,0.90,16.60,9.36,2.120333,...,0,0,0,0,0,0,0,0,0,0

In [2]:
indep=dataset[['PM2.5', 'PM10','NO','NO2','NOx','NH3','CO','SO2','O3']]
dep=dataset['AQI']

In [3]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['mse','mae'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\Madhu\Anaconda3\envs\ML\lib\site-packages\sklearn\ensemble\_forest.py:398: FutureWarning: Criterion 'mae' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='absolute_error'` which is equivalent.
  FutureWarning,

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [6]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   
# print classification report 
from sklearn.metrics import mean_squared_error
rmse=mean_squared_error(y_test,grid_predictions,squared=False)
print("The RMSE value for best parameter {}:".format(grid.best_params_),rmse)

The RMSE value for best parameter {'criterion': 'mae', 'max_features': 'sqrt', 'n_estimators': 100}: 29.066771458405427

In [7]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.163186,0.021224,0.008000,4.101908e-07,mse,auto,10,"{'criterion': 'mse', 'max_features': 'auto', '...",0.679441,0.614119,0.677503,0.632141,0.613727,0.643386,0.029416,12
1,1.144496,0.040275,0.027198,3.917693e-03,mse,auto,100,"{'criterion': 'mse', 'max_features': 'auto', '...",0.696868,0.639138,0.685535,0.672729,0.647630,0.668380,0.021956,8
2,0.084794,0.006399,0.009600,3.199577e-03,mse,sqrt,10,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.683256,0.630420,0.656611,0.642080,0.691925,0.660858,0.023512,11
3,0.674705,0.030582,0.029948,2.989038e-03,mse,sqrt,100,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.719768,0.692856,0.700112,0.676046,0.662802,0.690317,0.019649,3
4,0.070236,0.003135,0.003200,3.919367e-03,mse,log2,10,"{'criterion': 'mse', 'max_features': 'log2', '...",0.724467,0.677320,0.699526,0.651108,0.646116,0.679708,0.029490,5
5,0.644745,0.047620,0.022399,3.200173e-03,mse,log2,100,"{'criterion': 'mse', 'max_features': 'log2', '...",0.724792,0.688264,0.695946,0.682602,0.669637,0.692248,0.018401,2
6,0.900721,0.037040,0.001600,3.199577e-03,mae,auto,10,"{'criterion': 'mae', 'max_features': 'auto', '...",0.666013,0.645868,0.692252,0.689310,0.636736,0.666036,0.022335,9
7,9.517242,0.205664,0.020800,3.918296e-03,mae,auto,100,"{'criterion': 'mae', 'max_features': 'auto', '...",0.694574,0.642444,0.700377,0.683261,0.675280,0.679187,0.020335,6
8,0.420490,0.014346,0.005391,4.532983e-03,mae,sqrt,10,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.703405,0.646966,0.659963,0.683819,0.619111,0.662653,0.029182,10
9,3.953355,0.037076,0.023999,5.059956e-03,mae,sqrt,100,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.718085,0.707720,0.693096,0.686413,0.677235,0.696510,0.014672,1
10,0.403164,0.032236,0.004800,3.919289e-03,mae,log2,10,"{'criterion': 'mae', 'max_features': 'log2', '...",0.680757,0.695042,0.657655,0.652789,0.666193,0.670487,0.015523,7
11,4.341531,0.200550,0.033378,1.149259e-02,mae,log2,100,"{'criterion': 'mae', 'max_features': 'log2', '...",0.710760,0.694025,0.695102,0.661908,0.669833,0.686326,0.017897,4